pipeline {
    agent any

    environment {
        TOOL_DIR = "${WORKSPACE}/jenkins_test2/test_jenkins/ci-cd-tools"
    }

    stages {
        stage('git repo & clean'){
            steps {
                sh " rm -rf jenkins_test2"
                sh "git clone https://github.com/bjalouli/jenkins_test2.git"
                //sh "mvn clean -f jenkins_test2"
            }
        }
        stage('Build') {
            steps {
                sh "${TOOL_DIR}/build.sh ${WORKSPACE}/jenkins_test2/test_jenkins/Debug Debug all"
            }
        }
    }
}
